source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZDPageNavigationController_Example' do
  pod "ZDPageNavigationController", :path => "../"
end

target 'Tests' do
  pod "ZDPageNavigationController", :path => "../"
end
