source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZDPageNavigationController_Example', :exclusive => true do
  pod "ZDPageNavigationController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ZDPageNavigationController", :path => "../"

  
end
